// Generated by CoffeeScript 1.8.0
var joueurs;

joueurs = [];

socket.on("init_joueur", function(liste_joueurs) {
  joueurs = liste_joueurs;
  return console.log("Liste des joueurs init");
});

socket.on("nouveau_joueur", function(nouveauJoueur) {
  joueurs.push(nouveauJoueur);
  return console.log("Nouveau Joueur ajouté");
});
