// Generated by CoffeeScript 1.8.0
var controle_clavier, deplacement, idjoueur, joueurs;

idjoueur = null;

joueurs = [];

socket.on("init_joueur", function(liste_joueurs) {
  joueurs = liste_joueurs;
  idjoueur = liste_joueurs.length;
  return console.log("Liste des joueurs init");
});

socket.on("nouveau_joueur", function(nouveauJoueur) {
  joueurs.push(nouveauJoueur);
  return console.log("Nouveau Joueur ajouté");
});

controle_clavier = function() {
  var blocage;
  blocage = 1;
  window.onkeydown = function(event) {
    var e, key;
    if (blocage) {
      e = event || window.event;
      key = e.which || e.keyCode;
    }
    switch (key) {
      case 38:
        blocage = 0;
        deplacement("haut");
        setTimeout((function() {
          blocage = 1;
        }), 620);
        break;
      case 40:
        blocage = 0;
        deplacement("bas");
        setTimeout((function() {
          blocage = 1;
        }), 620);
        break;
      case 37:
        blocage = 0;
        deplacement("gauche");
        setTimeout((function() {
          blocage = 1;
        }), 620);
        break;
      case 39:
        blocage = 0;
        deplacement("droite");
        setTimeout((function() {
          blocage = 1;
        }), 620);
        break;
      default:
        return true;
    }
    return false;
  };
};

controle_clavier();

deplacement = function(direction) {
  return socket.emit("deplacement", {
    idjoueur: idjoueur,
    direction: direction
  });
};
