// Generated by CoffeeScript 1.8.0
var controle_clavier, deplacement, deplacement_joueur, idjoueur, joueurs;

idjoueur = null;

joueurs = [];

deplacement_joueur = function(id, direction) {
  if (direction === "haut") {
    joueurs[id].y = joueurs[id].y + 1;
  }
  if (direction === "bas") {
    joueurs[id].y = joueurs[id].y - 1;
  }
  if (direction === "droite") {
    joueurs[id].x = joueurs[id].x + 1;
  }
  if (direction === "gauche") {
    return joueurs[id].x = joueurs[id].x - 1;
  }
};

socket.on("init_joueur", function(liste_joueurs) {
  joueurs = liste_joueurs;
  idjoueur = liste_joueurs.length - 1;
  return console.log("Réception : Liste des joueurs init");
});

socket.on("nouveau_joueur", function(nouveauJoueur) {
  joueurs.push(nouveauJoueur);
  return console.log("Réception: Nouveau Joueur ajouté");
});

socket.on("deplacement_joueur", function(data) {
  deplacement_joueur(data.idjoueur, data.direction);
  return console.log("Réception: deplacement");
});

controle_clavier = function() {
  var blocage;
  blocage = 1;
  window.onkeydown = function(event) {
    var e, key;
    if (blocage) {
      e = event || window.event;
      key = e.which || e.keyCode;
    }
    switch (key) {
      case 38:
        blocage = 0;
        deplacement("haut");
        setTimeout((function() {
          blocage = 1;
        }), 620);
        break;
      case 40:
        blocage = 0;
        deplacement("bas");
        setTimeout((function() {
          blocage = 1;
        }), 620);
        break;
      case 37:
        blocage = 0;
        deplacement("gauche");
        setTimeout((function() {
          blocage = 1;
        }), 620);
        break;
      case 39:
        blocage = 0;
        deplacement("droite");
        setTimeout((function() {
          blocage = 1;
        }), 620);
        break;
      default:
        return true;
    }
    return false;
  };
};

controle_clavier();

deplacement = function(direction) {
  socket.emit("deplacement", {
    idjoueur: idjoueur,
    direction: direction
  });
  return false;
};
