// Generated by CoffeeScript 1.8.0
var Joueur, app, fs, handler, id, io, joueurs, nouveauJoueur, uniqueId;

app = require("http").createServer(handler);

io = require("socket.io")(app);

fs = require("fs");

app.listen(80);

console.log("Serveur OK");

handler = function(req, res) {
  fs.readFile(__dirname + "/index.html", function(err, data) {
    if (err) {
      res.writeHead(500);
      return res.end("Error loading index.html");
    }
    res.writeHead(200);
    res.end(data);
  });
};

uniqueId = function(length) {
  var id;
  if (length == null) {
    length = 8;
  }
  id = "";
  while (id.length < length) {
    id += Math.random().toString(36).substr(2);
  }
  return id.substr(0, length);
};

joueurs = [];

Joueur = (function() {
  function Joueur(id) {
    this.id = id;
    this.x = 0;
    this.y = 0;
  }

  return Joueur;

})();

io.on("connection", function(socket) {
  return console.log("Nouveau utilisateur");
});

id = uniqueId(20);

nouveauJoueur = new Joueur(id);

joueurs.push(nouveauJoueur);

socket.emit("init_joueur", joueurs);

socket.broadcast.emit("nouveau_joueur", nouveauJoueur);

return;
