// Generated by CoffeeScript 1.8.0
var Joueur, app, fs, handler, io, joueurs, uniqueId;

handler = function(req, res) {
  fs.readFile(__dirname + "/index.html", function(err, data) {
    if (err) {
      res.writeHead(500);
      return res.end("Error loading index.html");
    }
    res.writeHead(200);
    res.end(data);
  });
};

uniqueId = function(length) {
  var id;
  if (length == null) {
    length = 8;
  }
  id = "";
  while (id.length < length) {
    id += Math.random().toString(36).substr(2);
  }
  return id.substr(0, length);
};

app = require("http").createServer(handler);

io = require("socket.io")(app);

fs = require("fs");

app.listen(80);

console.log("Serveur OK");

joueurs = [];

Joueur = (function() {
  function Joueur(id) {
    this.id = id;
  }

  return Joueur;

})();

io.on("connection", function(socket) {
  var id, joueur, _i, _len;
  console.log("Nouveau utilisateur");
  id = uniqueId(20);
  joueurs.push(new Joueur(id));
  for (_i = 0, _len = joueurs.length; _i < _len; _i++) {
    joueur = joueurs[_i];
    console.log(joueur);
  }
});
